// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: sum.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdditionClient is the client API for Addition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdditionClient interface {
	Sum(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type additionClient struct {
	cc grpc.ClientConnInterface
}

func NewAdditionClient(cc grpc.ClientConnInterface) AdditionClient {
	return &additionClient{cc}
}

func (c *additionClient) Sum(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/sum.addition/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdditionServer is the server API for Addition service.
// All implementations must embed UnimplementedAdditionServer
// for forward compatibility
type AdditionServer interface {
	Sum(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAdditionServer()
}

// UnimplementedAdditionServer must be embedded to have forward compatible implementations.
type UnimplementedAdditionServer struct {
}

func (UnimplementedAdditionServer) Sum(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedAdditionServer) mustEmbedUnimplementedAdditionServer() {}

// UnsafeAdditionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdditionServer will
// result in compilation errors.
type UnsafeAdditionServer interface {
	mustEmbedUnimplementedAdditionServer()
}

func RegisterAdditionServer(s grpc.ServiceRegistrar, srv AdditionServer) {
	s.RegisterService(&Addition_ServiceDesc, srv)
}

func _Addition_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdditionServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sum.addition/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdditionServer).Sum(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Addition_ServiceDesc is the grpc.ServiceDesc for Addition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Addition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sum.addition",
	HandlerType: (*AdditionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _Addition_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sum.proto",
}
